<?php
  echo "
  <header>
    <nav class='navbar vl navbar-dark navbar-expand-md '>
      <!-- add background color  -->
      <div class='container-fluid'>
        <div class=''>
          <img class='ruby_intro' src='images/Ruby_intro.png' alt='ruby image'>
          <a class='navbar-brand ' href='index.php'>Ruby on Rails</a>
        </div>
        <div class='menu-small'>
          <div class='bar'>
            <div  >  </div>
            <div >  </div>
            <div >  </div>
                </div>
            <div class='small-menu'>
              <ul>
                <li class=' small-list nav-link '>
                  <!-- apply flex display to center the image and text -->
                  <a class=' ' href='index.php'>Home</a>
                </li>
                <li class=' small-list nav-link '>
                  <a class='' href='topic.php'>Topic</a>
                </li>
                <li class='small-list nav-link '>
                  <a class='' href='quiz.php'>Quiz</a>
                </li>
                <li class='small-list nav-link '>
                  <a  href='enhancement.php'>Enhancement</a>
                </li>
              </ul>
            </div>
        </div>
        <ul class='navbar-nav ms-auto'>
          <!-- bootstrap to make the menu horizontal  -->
          <li class=' de '>
            <!-- apply flex display to center the image and text -->
            <img class='ruby-icon' src='images/ruby_icon.png' alt='ruby icon'>
            <a class='nav-link ' href='index.php'>Home</a>
          </li>
          <li class=' de '>
            <img class='ruby-icon' src='images/ruby_icon.png' alt='ruby icon'>
            <a class='nav-link' href='topic.php'>Topic</a>
          </li>
          <li class='de '>
            <img class='ruby-icon' src='images/ruby_icon.png' alt='ruby icon'>
            <a class='nav-link' href='quiz.php'>Quiz</a>
          </li>
          <li class='de '>
            <img class='ruby-icon' src='images/ruby_icon.png' alt='ruby icon'>
            <a class='nav-link' href='enhancement.php'>Enhancement</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  ";

 ?>
