<?php

  echo "
  <footer>
    <div class='container-footer'>
      <div>
        <p class='p-us'>ABOUT US</p>
      </div>
      <div class=' footer-mail list-details'>
        <div>
          <a href='mailto:103509199@student.swin.edu.au'>Name: Hung</a>
        </div>
        <div>
          <a href='mailto:103107988@student.swin.edu.au'>Name: Kimlong</a>
        </div>
        <div>
          <a href='mailto:103996584@student.swin.edu.au'>Name: Dylan </a>
        </div>
        <div>
          <a href='mailto:104005449@student.swin.edu.au'>Name: Rogier </a>
        </div>
        <div>
          <a href='mailto:103999554@student.swin.edu.au'>Name: Delta </a>
        </div>
      </div>
    </div>
  </footer> ";

?>
